### ISSUE TITLE
Could not create entity: [40 instances are already running or stopped.]

### ISSUE THREAD

**Issue by natea** [comodit/demos#6]
When I try to deploy the broker, the following error occurs:

```
$ ./deploy-broker.py
Deploying Openshift Broker
Could not create entity: [40 instances are already running or stopped.]
```

**Comment by eschnou** [comment]
ComodIT failed at creating the instance due to an issue at the platform level. Looking at the error message I guess your cloud provider is complaining that you already have 40 instances running or stopped. Make sure you delete the unused instances or request an upgrade of the instance limits to solve this issue. If you keep on having troubles, please get in touch with our support at support@comodit.com.
